import {
  Archive,
  Bot,
  CheckSquare,
  FileText,
  Folder,
  type LucideIcon,
  Workflow,
} from 'lucide-react';
import { RESOURCE_TIME_COLUMN_WIDTH, TASK_AUTOMATION_COLUMN_WIDTH } from '@/data/tableColumns';

export type WorkspaceView = 'chat' | 'tasks' | 'automations' | 'artifacts' | 'context-files';
export type CreateMode = 'none' | 'task' | 'automation';

export interface PromptTemplate {
  id: string;
  text: string;
}

export interface NavigationItem {
  id: WorkspaceView;
  label: string;
  icon: LucideIcon;
}

export interface EmptyTableConfig {
  title: string;
  description: string;
  action: string;
}

export interface ResourceColumn {
  id: string;
  label: string;
  width?: string;
}

export const promptTemplates: PromptTemplate[] = [
  {
    id: '1',
    text: '列出 Chain287 常用只读巡检命令，我是区块链新人。',
  },
  {
    id: '2',
    text: '检查 Chain287 RPC 快照、同步状态、peer 数和链上模式。',
  },
  {
    id: '3',
    text: '给我 Chain287 验证者总览，采样最近 80 个块。',
  },
  {
    id: '4',
    text: '检查 Chain287 最近 120 个块是否有验证者出块异常。',
  },
  {
    id: '5',
    text: '统计 Chain287 最近 10 分钟验证者出块、tx、gasUsed 和余额变化。',
  },
  {
    id: '6',
    text: '查询一个 Chain287 地址 0x... 的余额和 nonce。',
  },
  {
    id: '7',
    text: '查询一笔 Chain287 交易 0x... 的详情和 receipt。',
  },
  {
    id: '8',
    text: '检查 Chain287 是否有验证者 jailed、未入集或未正常出块。',
  },
];

export const navigationItems: NavigationItem[] = [
  {
    id: 'tasks',
    label: 'Tasks',
    icon: CheckSquare,
  },
  {
    id: 'automations',
    label: 'Automations',
    icon: Workflow,
  },
  {
    id: 'artifacts',
    label: 'Artifacts',
    icon: FileText,
  },
  {
    id: 'context-files',
    label: 'Context files',
    icon: Folder,
  },
];

export const recentItems = ['Validator Health Report'];

export const resourceColumns: Record<Exclude<WorkspaceView, 'chat'>, ResourceColumn[]> = {
  tasks: [
    { id: 'name', label: 'Task name', width: 'minmax(420px, 1.8fr)' },
    { id: 'status', label: 'Status', width: '150px' },
    { id: 'priority', label: 'Priority', width: '130px' },
    { id: 'type', label: 'Type', width: '150px' },
    { id: 'automation', label: 'Automation', width: TASK_AUTOMATION_COLUMN_WIDTH },
    { id: 'updated', label: 'Last updated at', width: RESOURCE_TIME_COLUMN_WIDTH },
  ],
  automations: [
    { id: 'name', label: 'Name', width: 'minmax(260px, 1.4fr)' },
    { id: 'trigger', label: 'Trigger', width: '170px' },
    { id: 'status', label: 'Status', width: '150px' },
    { id: 'enabled', label: 'Enabled', width: '150px' },
    { id: 'triggered', label: 'Last triggered', width: RESOURCE_TIME_COLUMN_WIDTH },
    { id: 'created', label: 'Created', width: RESOURCE_TIME_COLUMN_WIDTH },
  ],
  artifacts: [
    { id: 'name', label: 'Name', width: 'minmax(280px, 1.5fr)' },
    { id: 'type', label: 'Type', width: '160px' },
    { id: 'size', label: 'Size', width: '140px' },
    { id: 'created', label: 'Created', width: RESOURCE_TIME_COLUMN_WIDTH },
  ],
  'context-files': [
    { id: 'name', label: 'Name', width: 'minmax(320px, 1.6fr)' },
    { id: 'status', label: 'Status', width: '170px' },
    { id: 'uploaded', label: 'Date uploaded', width: RESOURCE_TIME_COLUMN_WIDTH },
  ],
};

export const emptyTableConfig: Record<Exclude<WorkspaceView, 'chat'>, EmptyTableConfig> = {
  tasks: {
    title: 'No tasks found',
    description: 'Status changes from tasks delegated to the NetX SRE Agent will appear here.',
    action: 'Create task',
  },
  automations: {
    title: 'No automations',
    description: 'Create an automation to run tasks on a schedule.',
    action: 'Create automation',
  },
  artifacts: {
    title: 'No artifacts',
    description: 'Artifacts generated by delegated work will appear here.',
    action: 'Upload artifact',
  },
  'context-files': {
    title: 'No context files yet.',
    description: 'Upload runbooks, node inventories, or policies to give the agent more context.',
    action: 'Upload file',
  },
};

export const topUtilityIcons = [Bot, Archive];
