import {
  Archive,
  Bot,
  CheckSquare,
  FileText,
  Folder,
  type LucideIcon,
  Workflow,
} from 'lucide-react';

export type WorkspaceView = 'chat' | 'tasks' | 'automations' | 'artifacts' | 'context-files';
export type CreateMode = 'none' | 'task' | 'automation';

export interface PromptTemplate {
  id: string;
  text: string;
}

export interface NavigationItem {
  id: WorkspaceView;
  label: string;
  icon: LucideIcon;
}

export interface EmptyTableConfig {
  title: string;
  description: string;
  action: string;
}

export interface ResourceColumn {
  id: string;
  label: string;
  width?: string;
}

export const promptTemplates: PromptTemplate[] = [
  {
    id: '1',
    text: 'Find validator nodes with abnormal block production and create an HTML report.',
  },
  {
    id: '2',
    text: 'Check NetX Chain RPC latency and peer count every 12 hours.',
  },
  {
    id: '3',
    text: 'Investigate sync anomalies in the last 7 days. Correlate logs, peer connections, and validator uptime.',
  },
  {
    id: '4',
    text: 'Automate validator health alerts for peerCount below 3 and post to Slack #netx-alerts.',
  },
  {
    id: '5',
    text: 'What was validator performance in June 2026, and how did it change compared to the prior month?',
  },
  {
    id: '6',
    text: 'Summarize node resource trends and recovery opportunities in an executive-ready report in ppt.',
  },
  {
    id: '7',
    text: 'Do I have any validators at risk of being jailed? What are the recovery procedures?',
  },
  {
    id: '8',
    text: 'Create a Jira ticket in space ENG summarizing validator anomalies and recommended actions per instance.',
  },
];

export const navigationItems: NavigationItem[] = [
  {
    id: 'tasks',
    label: 'Tasks',
    icon: CheckSquare,
  },
  {
    id: 'automations',
    label: 'Automations',
    icon: Workflow,
  },
  {
    id: 'artifacts',
    label: 'Artifacts',
    icon: FileText,
  },
  {
    id: 'context-files',
    label: 'Context files',
    icon: Folder,
  },
];

export const recentItems = ['Validator Health Report'];

export const resourceColumns: Record<Exclude<WorkspaceView, 'chat'>, ResourceColumn[]> = {
  tasks: [
    { id: 'name', label: 'Task name', width: 'minmax(240px, 1.4fr)' },
    { id: 'status', label: 'Status', width: '150px' },
    { id: 'priority', label: 'Priority', width: '130px' },
    { id: 'type', label: 'Type', width: '150px' },
    { id: 'automation', label: 'Automation', width: '160px' },
    { id: 'updated', label: 'Last updated at', width: '210px' },
  ],
  automations: [
    { id: 'name', label: 'Name', width: 'minmax(260px, 1.4fr)' },
    { id: 'trigger', label: 'Trigger', width: '170px' },
    { id: 'status', label: 'Status', width: '150px' },
    { id: 'enabled', label: 'Enabled', width: '150px' },
    { id: 'triggered', label: 'Last triggered', width: '210px' },
    { id: 'created', label: 'Created', width: '180px' },
  ],
  artifacts: [
    { id: 'name', label: 'Name', width: 'minmax(280px, 1.5fr)' },
    { id: 'type', label: 'Type', width: '160px' },
    { id: 'size', label: 'Size', width: '140px' },
    { id: 'created', label: 'Created', width: '210px' },
  ],
  'context-files': [
    { id: 'name', label: 'Name', width: 'minmax(320px, 1.6fr)' },
    { id: 'status', label: 'Status', width: '170px' },
    { id: 'uploaded', label: 'Date uploaded', width: '210px' },
  ],
};

export const emptyTableConfig: Record<Exclude<WorkspaceView, 'chat'>, EmptyTableConfig> = {
  tasks: {
    title: 'No tasks found',
    description: 'Status changes from tasks delegated to the NetX SRE Agent will appear here.',
    action: 'Create tasks',
  },
  automations: {
    title: 'No automations',
    description: 'Create an automation to run tasks on a schedule or in response to events.',
    action: 'Create automation',
  },
  artifacts: {
    title: 'No artifacts',
    description: 'Artifacts generated by delegated work will appear here.',
    action: 'Upload artifact',
  },
  'context-files': {
    title: 'No context files yet.',
    description: 'Upload runbooks, node inventories, or policies to give the agent more context.',
    action: 'Upload file',
  },
};

export const topUtilityIcons = [Bot, Archive];
